### ISSUE TITLE
Issue with setup.py

### ISSUE THREAD

**Issue by Harrydirk41** [kyonofx/mlcgmd#1]
I got the following error when installing:

Obtaining file:///C:/Users/harry/OneDrive/%E6%A1%8C%E9%9D%A2/Phd/Summer/graph/code/mlcgmd-main/mlcgmd-main
  Preparing metadata (setup.py) ... done
Installing collected packages: graphwm
  Running setup.py develop for graphwm
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [38 lines of output]
        running develop
        running egg_info
        writing graphwm.egg-info\PKG-INFO
        writing dependency_links to graphwm.egg-info\dependency_links.txt
        writing top-level names to graphwm.egg-info\top_level.txt
        reading manifest file 'graphwm.egg-info\SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'graphwm.egg-info\SOURCES.txt'
        running build_ext
        Creating c:\users\harry\anaconda3\envs\mlcgmd\lib\site-packages\graphwm.egg-link (link to .)
        C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\harry\OneDrive\\u684c\u9762\Phd\Summer\graph\code\mlcgmd-main\mlcgmd-main\setup.py", line 3, in <module>
            setup(
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
            return run_commands(dist)
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
            dist.run_commands()
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\dist.py", line 1214, in run_command
            super().run_command(command)
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
            cmd_obj.run()
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\develop.py", line 126, in install_for_development
            f.write(self.egg_path + "\n" + self.setup_path)
          File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\encodings\cp1252.py", line 19, in encode
            return codecs.charmap_encode(input,self.errors,encoding_table)[0]
        UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-25: character maps to <undefined>
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [38 lines of output]
    running develop
    running egg_info
    writing graphwm.egg-info\PKG-INFO
    writing dependency_links to graphwm.egg-info\dependency_links.txt
    writing top-level names to graphwm.egg-info\top_level.txt
    reading manifest file 'graphwm.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'graphwm.egg-info\SOURCES.txt'
    running build_ext
    Creating c:\users\harry\anaconda3\envs\mlcgmd\lib\site-packages\graphwm.egg-link (link to .)
    C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\harry\OneDrive\\u684c\u9762\Phd\Summer\graph\code\mlcgmd-main\mlcgmd-main\setup.py", line 3, in <module>
        setup(
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\dist.py", line 1214, in run_command
        super().run_command(command)
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\site-packages\setuptools\command\develop.py", line 126, in install_for_development
        f.write(self.egg_path + "\n" + self.setup_path)
      File "C:\Users\harry\anaconda3\envs\mlcgmd\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-25: character maps to <undefined>
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by kyonofx** [comment]
Hi,

I am not sure what is the problem, seems like you are on a Windows machine? Could you try using a Linux machine if you have access to any?

Just by looking at your error message, maybe you could try installing to an all-English path?

Also, this code was only tested on a Linux machine with Ubuntu>=18.04. It is unclear whether it would work on a Windows machine.

Thanks,
Xiang

**Comment by kyonofx** [comment]
Marked as closed. Feel free to reopen if you have further questions.
